/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 19:15:56 GMT 2018
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleStaticSut;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SimpleStaticSut_ESTest extends SimpleStaticSut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        SimpleStaticSut.isSecretQuadraticEquationSolution(733675332852L);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // long overflow
         //
         verifyException("java.lang.Math", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = SimpleStaticSut.isSecretQuadraticEquationSolution(1L);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = SimpleStaticSut.isSecretQuadraticEquationSolution((-18L));
      assertFalse(boolean0);
  }
}
